yay -S --noconfirm gum-bin
yay -S --noconfirm zsh-theme-powerlevel10k-git
yay -S --noconfirm i3lock-fancy-git
yay -S --noconfirm lightdm-settings
yay -S --noconfirm vscodium-bin
yay -S --noconfirm ttf-meslo-nerd-font-powerlevel10k
yay -S --noconfirm ttf-dejavu-sans-mono-powerline-git
yay -S --noconfirm polkit-dumb-agent-git
yay -S --noconfirm github-desktop-bin
